"""Parity registry: enumerate every tool, skill, hook event, and agent, check
parity.json covers each for every harness, and render PARITY.md.

Usage: python tools/render_parity.py [--check]
"""

from __future__ import annotations

import asyncio
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

HARNESS_NAMES = ("claude-code", "codex")
STATUSES = ("full", "partial", "waived", "n/a")
REGISTRY = REPO / "parity.json"
OUTPUT = REPO / "PARITY.md"
HOOK_FILES = (REPO / "hooks" / "hooks.json", REPO / "adapters" / "codex" / "hooks.json")


def registered_tools() -> list[str]:
    from fastmcp import FastMCP

    from vibe_cognition.tools import register_all_tools

    mcp = FastMCP("parity")
    register_all_tools(mcp)
    return sorted(t.name for t in asyncio.run(mcp.list_tools()))


def enumerate_items() -> list[str]:
    items = [f"tool:{n}" for n in registered_tools()]
    items += sorted(f"skill:{p.parent.name}" for p in (REPO / "skills-src").glob("*/SKILL.md"))
    events: set[str] = set()
    for hf in HOOK_FILES:
        events.update(json.loads(hf.read_text(encoding="utf-8"))["hooks"].keys())
    items += sorted(f"hook:{e}" for e in events)
    items += sorted(f"agent:{p.stem}" for p in (REPO / "agents-src").glob("*.md"))
    return items


def load_registry() -> dict:
    return json.loads(REGISTRY.read_text(encoding="utf-8"))


JOURNAL = REPO / ".cognition" / "journal.jsonl"


def _gate_exists(node_id: str) -> bool:
    if not JOURNAL.exists():
        return False
    needle = f'"id": "{node_id}"'
    with JOURNAL.open(encoding="utf-8") as fh:
        return any(needle in line and '"type": "episode"' in line for line in fh)


def _evidence_ok(evidence: str) -> bool:
    if evidence.startswith("gate:"):
        return bool(re.fullmatch(r"gate:[0-9a-f]{12}", evidence)) and _gate_exists(evidence[5:])
    path, _, func = evidence.partition("::")
    target = REPO / path
    if not target.exists():
        return False
    if func:
        return f"def {func}(" in target.read_text(encoding="utf-8")
    return True


def validate(registry: dict) -> list[str]:
    problems: list[str] = []
    rows = registry.get("items", {})
    for item in enumerate_items():
        row = rows.get(item)
        if row is None:
            problems.append(f"missing parity row: {item}")
            continue
        for hz in HARNESS_NAMES:
            cell = row.get(hz)
            if cell is None:
                problems.append(f"{item}: no entry for {hz}")
                continue
            status = cell.get("status")
            if status not in STATUSES:
                problems.append(f"{item}/{hz}: bad status {status!r}")
                continue
            if status == "full":
                ev = cell.get("evidence", "")
                if not ev or not _evidence_ok(ev):
                    problems.append(f"{item}/{hz}: 'full' needs evidence naming an existing test or gate:<episode>")
            elif not cell.get("note"):
                problems.append(f"{item}/{hz}: status {status} needs a note")
    known = set(enumerate_items())
    for item in rows:
        if item not in known:
            problems.append(f"stale parity row (no such item): {item}")
    return problems


def render_md(registry: dict) -> str:
    rows = registry["items"]
    lines = ["# Harness parity", "", "Generated by `tools/render_parity.py` from `parity.json` — do not edit.", ""]
    lines.append("| Item | " + " | ".join(HARNESS_NAMES) + " |")
    lines.append("|---|" + "---|" * len(HARNESS_NAMES))
    for item in enumerate_items():
        cells = []
        for hz in HARNESS_NAMES:
            cell = rows[item][hz]
            text = cell["status"]
            if cell.get("note"):
                text += f" — {cell['note']}"
            cells.append(text)
        lines.append(f"| `{item}` | " + " | ".join(cells) + " |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    registry = load_registry()
    problems = validate(registry)
    md = render_md(registry) if not problems else ""
    if "--check" in argv:
        if not problems and OUTPUT.read_text(encoding="utf-8") != md:
            problems.append("PARITY.md is stale — run tools/render_parity.py")
    elif not problems:
        OUTPUT.write_text(md, encoding="utf-8", newline="\n")
        print(f"wrote {OUTPUT.name} ({len(registry['items'])} items)")
    for p in problems:
        print(p)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
